name: Dibs Seize
description: Acquire a position in a Dibs queue

inputs:
  queue:
    description: Dibs queue to acquire
    required: true
  slack_team:
    description: The Slack short name for your organization
    required: true
  slack_team_id:
    description: The Slack Team ID for your organization
    required: true
  slack_username:
    description: The Slack username of the person getting in the queue
    required: true
  slack_channel_id:
    description: The Slack Channel ID for queue notifications (optional)
    required: false
  duration:
    description: How long to stay queue leader before auto-release (optional)
    required: false

outputs:
  release-key:
    description: Secret key required to release the Dibs lock
    value: ${{ steps.seize.outputs.release-key }}

runs:
  using: composite
  steps:
    - name: Seize Dibs resource
      shell: bash
      env:
        DIBS_API_KEY: ${{ env.DIBS_API_KEY }}
        DIBS_QUEUE: ${{ inputs.queue }}
        SLACK_TEAM: ${{ inputs.slack_team }}
        SLACK_TEAM_ID: ${{ inputs.slack_team_id }}
        SLACK_USERNAME: ${{ inputs.slack_username }}
        SLACK_CHANNEL_ID: ${{ inputs.slack_channel_id }}
        DIBS_DURATION: ${{ inputs.duration }}
      run: |
        result=$(python3 "$GITHUB_ACTION_PATH/seize.py")
        echo "release-key=$result" >> "$GITHUB_OUTPUT"
